export type ProjectItem = {
  id: string;
  Name: string;
  "Roll Number": string;
  "LDAP-ID": string;
  "Mail-ID": string;
  "Contact Number": string;
  "Year of Study": string;
  "Academic Department": string;
  "Degree Enrolled for": string;
  "Co-Mentor": string;
  "Co-Mentor Name": string;
  "Co-Mentor Roll": string;
  "Co-Mentor LDAP": string;
  "Co-Mentor Mail": string;
  "Co-Mentor Contact": string;
  "Co-Mentor Year": string;
  "Co-Mentor Dept": string;
  "Co-Mentor Degree": string;
  "Project Domain 1": string;
  "Project Domain 2": string;
  "Project Title": string;
  "Project Description": string;
  Difficulty: string;
  "Project Type": string;
  "Duration (weeks)": string;
  "Weekly Hours": string;
  "Number of Mentees": string;
  "Pre-Requisites": string;
  "Project Image": string;
  "Previously Completed?": string;
  "Project Experience": string;
  "Resources Link": string;
  Comments: string;
  InWishList : string;
};
